language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.init()'
  - if [ $JULIAVERSION = "julianightlies" ]; then julia -e 'Pkg.add("Ipopt")'; fi
  - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("FiniteStateMachine"))`); Pkg.pin("FiniteStateMachine"); Pkg.resolve()'
  - julia -e 'for p in split(ENV["PKGADD"],";") Pkg.add(p) end'
  - if [ $JULIAVERSION = "julianightlies" ]; then julia --code-coverage test/runtests.jl; fi
  - if [ $JULIAVERSION = "juliareleases" ]; then julia test/runtests.jl; fi
  - julia test/runtests.jl
after_success:
  - if [ $JULIAVERSION = "julianightlies" ]; then julia -e 'cd(Pkg.dir("FiniteStateMachine")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
